### ISSUE TITLE
dah bagus.

### ISSUE THREAD

**Issue by angganesia** [Keito-Klein/Vertibus#1]
untuk fiturnya udah bagus tuh, cuma butuh kulik" lagi buat run bot nya di versi latest.
kembangin lagi bro. oh ya ada masalah di mongoDB nya.

**Comment by Keito-Klein** [comment]
> untuk fiturnya udah bagus tuh, cuma butuh kulik" lagi buat run bot nya di versi latest. kembangin lagi bro. oh ya ada masalah di mongoDB nya.

mongoDBnya ganti aja bro, wkwk. itu ku encrypt krn pke mongoDB gw sendiri
